### ISSUE TITLE
missing file 

### ISSUE THREAD

**Issue by OmerMagdy** [JaywongWang/SST-Tensorflow#1]
Hello,
I was trying to run the code and when I ran train.py i had this error message:

"OSError: Unable to open file (unable to open file: name = 'dataset/thumos14/features/thumos14_c3d_fc6.hdf5', errno = 2, error message = 'No such file or directory')"

I would like to know how to create that missing file in features folder or if you have a version of it and you could send it to me I would appreciate it.

**Comment by JaywongWang** [comment]
Hi, sorry about the missing file. I will upload the feature file (~2.4G) recently.

**Comment by JaywongWang** [comment]
Hi, here is the extracted [C3D](https://pan.baidu.com/s/1ggMHZ71) feature file for THUMOS14 dataset.

**Comment by OmerMagdy** [comment]
thank you for your answer and uploading the file .
I would like to know how to create this feature file to generate it for my dataset or if you have a code for generating  it and you could send it to me I would appreciate it.

**Comment by JaywongWang** [comment]
The features were actually provided by another colleague. Her code is [here](https://github.com/yyuanad/Pytorch_C3D_Feature_Extractor).

**Comment by OmerMagdy** [comment]
thank you very much
