### ISSUE TITLE
Feature doesn't match

### ISSUE THREAD

**Issue by Amose-Yao** [JaywongWang/SST-Tensorflow#7]
Hi
Thanks for the code.
I try to extract the feature according to the github address you mentioned(https://github.com/yyuanad/Pytorch_C3D_Feature_Extractor). But I got a complete different feature file, which contains huge values. But in your feature file the value is small. Could you please show me how you extract the feature from videos.

**Comment by JaywongWang** [comment]
Hi,
Possibly because the original code has been updated.
Please refer to my code for extracting C3D features: https://drive.google.com/open?id=1Jcgyr6QwxB4mR3eceIzv4KESBuKCvQxl
I sampled video frames at original fps and extracted C3D with 16-frame snippet.
